#!/bin/bash
# https://packages.sury.org/php/

# Requirements
sudo apt-get -y install lsb-release;

# Repositories and keys
wget -O- https://packages.sury.org/php/apt.gpg | sudo apt-key add -;
sudo bash -c "cat << EOF > /etc/apt/sources.list.d/sury.list
# Sury Packages
deb https://packages.sury.org/php/ $(lsb_release -sc) main
EOF";
sudo apt-get update;

# Install software
sudo apt-get install -y php7.0-fpm php7.0-cgi php7.0-cli php7.0-xdebug php7.0-opcache php7.0-xml php7.0-json php7.0-soap php7.0-mbstring php7.0-mcrypt php7.0-gmp php7.0-curl php7.0-gd php7.0-imagick php7.0-ldap php7.0-redis php7.0-mysql php7.0-pgsql php7.0-sqlite3;

# Verifications
$(which php7.0) -v;

